---
- name: Ensure kvm relevant packages are installed
  ansible.builtin.apt:
    name: [qemu-kvm, libvirt-clients, libvirt-daemon-system,
           python3-libvirt, python3-lxml]
    state: present
  tags: kvm

- name: Add local system user to libvirtd group
  ansible.builtin.user:
    name: "{{ sysuser }}"
    append: true
    groups: libvirt
  tags: kvm
  ignore_errors: "{{ ansible_check_mode }}"

- name: Add kvm_intel nested flag
  ansible.builtin.template:
    src: kvm_intel_nested.conf.j2
    dest: /etc/modprobe.d/kvm_intel_nested.conf
    mode: 0644
    owner: root
    group: root

- name: Ensure kvm module is available
  community.general.modprobe:
    name: kvm_intel
    state: present

- name: Copy sanity test script to host
  ansible.builtin.copy:
    src: files/kvm_sanity_check.sh
    dest: /usr/local/bin/kvm_sanity_check.sh
    mode: 0755
    owner: root
    group: root
