

- name: Ensure kvm relevant packages are installed
  apt: name={{ item }} state=present
  with_items:
  - qemu-kvm
  - libvirt-bin
  tags: kvm

- name: add local system user to libvirtd group
  user: name={{ sysuser }} append=yes groups=libvirt
  tags: kvm

