

- name: Ensure kvm relevant packages are installed
  apt:
    name: [qemu-kvm,
          libvirt-clients,
          libvirt-daemon-system]
    state: present
  tags: kvm

- name: add local system user to libvirtd group
  user: name={{ sysuser }} append=yes groups=libvirt
  tags: kvm
  ignore_errors: "{{ ansible_check_mode }}"

- name: add kvm_intel nested flag
  template:
    src: kvm_intel_nested.conf.j2
    dest: /etc/modprobe.d/kvm_intel_nested.conf
    mode: 0644
    owner: root
    group: root
  register: modprobe_kvm_conf

- name: remove kvm module
  command: rmmod kvm_intel
  when: modprobe_kvm_conf.changed and not kvm_provision_only
  ignore_errors: true

- name: modprobe kvm module
  command: modprobe kvm_intel
  when: modprobe_kvm_conf.changed and not kvm_provision_only

- name: copy sanity test script to host
  copy:
    src: files/kvm_sanity_check.sh
    dest: /usr/local/bin/kvm_sanity_check.sh
    mode: 0755
    owner: root
    group: root
