- name: Install ovs bridge
  become: true
  ansible.builtin.import_tasks: install-ovs-switch.yml
  when: install_ovs
  tags:
  - ovs
  - install

- name: Config ovs bridge
  become: true
  ansible.builtin.import_tasks: setup-ovs-switch.yml
  when: install_ovs
  tags:
  - ovs
  - config

- name: Include kvm system part
  ansible.builtin.import_tasks: install-kvm.yml
  become: true
  tags:
  - kvm
  - install

- name: Configure libvirt
  ansible.builtin.import_tasks: setup-libvirt.yml
  become: true
  tags:
  - kvm
  - config

- name: Include vagrant privileged part
  ansible.builtin.import_tasks: vagrant-become.yml
  become: true
  when: install_vagrant
  tags:
  - vagrant
  - install

- name: Include vagrant userspace part
  ansible.builtin.import_tasks: vagrant-userspace.yml
  become: true
  when: install_vagrant
  tags:
  - vagrant
  - config

- name: Install nfsd part
  ansible.builtin.import_tasks: nfsd-server.yml
  become: true
  when: install_nfsd
  tags:
  - nfs
  - install
