- name: include kvm+vagant systempart
  import_tasks: kvm-system.yml
  become: yes

- name: include vagrant privileged part
  import_tasks: vagrant-become.yml
  become: yes
  when: install_vagrant

- name: include vagrant userspace part
  import_tasks: vagrant-userspace.yml
  become: no
  when: install_vagrant

- import_tasks: nfsd-server.yml
  become: yes
  when: install_nfsd
