

- name: Ensure kvm relevant packages are installed
  apt: name={{ item }} state=present
  with_items:
  - qemu-kvm
  - libvirt-bin
  tags: kvm

- name: add local system user to libvirtd group
  user: name={{ sysuser }} append=yes groups=libvirt
  tags: kvm

- name: install vagrant
  apt: name={{ item }} state=present
  with_items:
  - vagrant 
  - libxslt1-dev 
  - libxml2-dev 
  - libvirt-dev 
  - zlib1g-dev
  - ansible
  tags: kvm
  when: install_vagrant

