- name: Install nfsd packages
  ansible.builtin.apt:
    name: [nfs-common,
           nfs-kernel-server,
           sudo]     # sudo is needed for vagrant
    state: present

- name: Create sudoers file
  ansible.builtin.template:
    src: templates/sudoers_vagrant.j2
    dest: /etc/sudoers.d/vagrant_nfs
    mode: 0644
    owner: root
    group: root
  when: install_vagrant
