- name: install nfsd packages
  apt:
    name: [nfs-common,
          nfs-kernel-server,
          sudo]     # sudo is needed for vagrant
    state: present

- name: create sudoers file
  template:
    src: templates/sudoers_vagrant.j2
    dest: /etc/sudoers.d/vagrant_nfs
    mode: 0644
    owner: root
    group: root
