# set up work switch
# this is for the virtual machines to connect to.

# Create a bridge named ovs-br0
- name: create ovs bridge
  openvswitch_bridge: bridge={{ bridge_name }} state=present
  tags: ovs

#- name: check for phys port
#  shell:  ovs-vsctl list-ifaces {{ bridge_name }} | grep {{ phys_device }}
#  register: ovs_phys_port_not_present
#  changed_when: false
#  failed_when: false
#  
#- debug: var=ovs_phys_port_not_present

- name: add physical interface to bridge
  openvswitch_port: bridge={{ bridge_name }} port={{ phys_device }} state=present   
  tags: ovs

#  when: ovs_phys_port_not_present.rc

- name: create vlan interface
  openvswitch_port: bridge={{ bridge_name }} port=vif_{{ item.name }} state=present 
                    set="interface vif_{{ item.name }} type=internal"
  with_items: "{{ bridge_LANs }}"
  tags: ovs


- name: set vlan tags
  openvswitch_port: bridge={{ bridge_name }} port=vif_{{ item.name }} state=present 
                    set="port vif_{{ item.name }} tag={{ item.vlanid }}"
  with_items: "{{ bridge_LANs }}"
  tags: ovs


