# user config to make vagrant work

- name: check if plugin is already installed
  shell: "vagrant plugin list | grep vagrant-libvirt"
  register: vagrant_libvirt_not_installed
  changed_when: false
  when: install_vagrant

- name: install vagrant plugin
  shell: vagrant plugin install vagrant-libvirt
  when: install_vagrant and vagrant_libvirt_not_installed.rc
