# user config to make vagrant work

- name: check if plugin is already installed
  shell: "vagrant plugin list | grep vagrant-libvirt"
  register: vagrant_libvirt_not_installed
  changed_when: false
  failed_when: false

- debug: var=vagrant_libvirt_not_installed

- name: install vagrant plugin
  shell: vagrant plugin install vagrant-libvirt
  when: vagrant_libvirt_not_installed.rc

