# privileged operation to install vagrant

- name: install vagrant
  apt: name={{ item }} state=present
  with_items:
  - vagrant 
  - libxslt1-dev 
  - libxml2-dev 
  - libvirt-dev 
  - zlib1g-dev
  - ansible
  tags: vagrant

