# user config to make vagrant work

- name: create vagrant directory
  file: path=~/.vagrant.d state=directory mode=0755

- name: add user Vagrantfile
  template: src=user_vagrantfile.j2
            dest=~/.vagrant.d/Vagrantfile
            mode=0644
