# user config to make vagrant work

- name: check if plugin is already installed
  shell: "vagrant plugin list | grep vagrant-libvirt"
  register: vagrant_libvirt_installed
  changed_when: false

- name: install vagrant plugin
  shell: vagrant plugin install vagrant-libvirt
  when: not vagrant_libvirt_installed

