# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Every Vagrant virtual environment requires a box to build off of.

  config.vm.define "test-kvm-stretch" do |deb|
    deb.vm.box = "debian/stretch64"
    deb.vm.hostname = "test-kvm-stretch"
    deb.vm.network :private_network, :ip => "192.168.128.3"
  end

  config.vm.define "test-kvm-buster" do |deb|
    deb.vm.box = "debian/buster64"
    deb.vm.hostname = "test-kvm-buster"
    deb.vm.network :private_network, :ip => "192.168.128.3"
  end

  config.vm.provider :libvirt do |libvirt|
    libvirt.host = ""
    libvirt.nested = true
    libvirt.memory = 2048
  end

  config.vm.synced_folder "./files", "/vagrant", disabled: true

  config.vm.provision "ansible" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "provision.yml"
  end

end
