# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Every Vagrant virtual environment requires a box to build off of.

  config.vm.box = "debian/stretch64"
  config.vm.hostname = "server-kvm-test"

  config.vm.provider :libvirt do |libvirt|
    libvirt.host = ""
    libvirt.nested = true
    libvirt.memory = 2048
  end

  config.vm.synced_folder "./files", "/vagrant", disabled: false

  config.vm.network :public_network,
      :dev => "ovs-br0",
      :type => "bridge",
      :ovs => true,
      :auto_config => false

  config.vm.provision "shell",
    inline: "apt-get update && apt-get upgrade"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "test.yml"
  end

end
